image: registry.gitlab.com/gatecoin/backend:dotnetcore

stages:
  - build
  - publish

build_package:
  stage: buildAndPublish
  artifacts:
    paths:
      - packages
    expire_in: 6 month
  script:
    - bash build.sh Release "$CI_JOB_ID" "packages"
    - bash publish.sh "https://gds.myget.org/F/public/api/v2/package" "$MYGET_API_KEY_PUBLIC" "packages"


